name: Deploy Flask App

on:
  push:
    branches:
      - main  # Deploys when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Fix SSH Permissions
        run: chmod 700 ~/.ssh

      - name: Deploy to EC2
        run: |
          ssh ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            set -x
            cd /home/ec2-user/flask-app || exit 1
            git pull origin main || exit 1
            docker-compose down || exit 1
            docker-compose up --build -d || exit 1
          EOF
